### PR TITLE
Add Polygon USDC to token list

### PR DESCRIPTION
**Pull request by gnardini**

### CODE REVIEW

**Review by jophish — APPROVED** [review]

**Review by jeanregisser — COMMENTED** [review]
The image is too small, can you upload a 256x256 one?

**Comment by jeanregisser** [comment]
Thanks, it's quite pixelated though 😢
No better one?

**Comment by jeanregisser** [comment]
Amazing 🙌

**Comment by gnardini** [comment]
Joe found a better one :D

**Pull request merged**
