### PR TITLE
Update tokens-info.json

### PR DESCRIPTION
**Pull request by Pasarnft**
{
    "address": "0x1da12e0bb9cf5de3e6cbdde427ffd9fe6d4df970",
    "decimals": 18,
    "imageUrl": "https://raw.githubusercontent.com/valora-inc/address-metadata/main/assets/tokens/GUIDE.png)",
    "name": "GUIDE",
    "symbol": "GUIDE"
  }

### CODE REVIEW

**Comment by Pasarnft** [comment]
GUIDE TOKEN LISTING

**Comment by Pasarnft** [comment]
Here the image link, because upload is disable
https://we.tl/t-Xax53onje8

**Comment by MuckT** [comment]
@Pasarnft please add the image in your Pull Request in the `assets/tokens` folder. The update the `imageUrl` to be `https://raw.githubusercontent.com/valora-inc/address-metadata/main/assets/tokens/<tokenName>.png`

**Comment by Pasarnft** [comment]
GUIDE

**Comment by MuckT** [comment]
Closed in favor of #33

**Pull request closed without merging**
