### PR TITLE
feat: add guide token

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Adds the Guide Token and Addresses
Mainnet: [https://explorer.celo.org/address/0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970](0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970)
Alfajores:  ?

### CODE REVIEW

**Comment by MuckT** [comment]
@Pasarnft can you provide the Alfajores address for the GUIDE token?

**Comment by Pasarnft** [comment]
> ### Description
> Adds the Guide Token and Addresses Mainnet: [https://explorer.celo.org/address/0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970](0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970) Alfajores: ?

Main net

**Comment by Pasarnft** [comment]
> ### Description
> Adds the Guide Token and Addresses Mainnet: [https://explorer.celo.org/address/0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970](0x1Da12E0bB9cf5DE3E6cbdde427FFD9fe6D4df970) Alfajores: ?

Its main net.the token was done by 3rd party dx.app

**Comment by Pasarnft** [comment]
> @Pasarnft can you provide the Alfajores address for the GUIDE token?

Dx.app the 3rd party make the contract dont support celo address testnet

**Comment by Pasarnft** [comment]
Hello any update?

**Comment by Pasarnft** [comment]
@MuckT any update?

**Comment by MuckT** [comment]
@Pasarnft we're looking into it!

**Comment by gsalaiz-Valora** [comment]
Hi @Pasarnft we won't be able to list your token because it doesn't comply with the minimum requirements: 

The token has to be reviewed and approved by at least one partner organization in the Celo ecosystem
Minimum liquidity of $20K for every pair in the route from asset to cUSD

These criteria are to guard our users against potentially fraudulent activity such as pull rugs. Once you comply with these requirements we can review again your request.

Best

**Pull request closed without merging**
