### PR TITLE
Add ETHIX token in mainnet and alfajores

### PR DESCRIPTION
**Pull request by eun-plata**

### CODE REVIEW

**Comment by MuckT** [comment]
@eun-plata can you resize the ETHIX.png to be 256 x 256? The tests should pass then and this can be merged.

**Comment by eun-plata** [comment]
> @eun-plata can you resize the ETHIX.png to be 256 x 256? The tests should pass then and this can be merged.

@MuckT on it! I'll let you know when it's done.

**Comment by eun-plata** [comment]
Hi again @MuckT 
Just pushed the last commit! Thank you for your help!!

**Review by MuckT — APPROVED** [review]
[Alfajores Contract](https://alfajores-blockscout.celo-testnet.org/address/0x4620D7a5F58f77eeE69A38AfdAa8f2FfB10b42b6/transactions)
[Mainnet Contract](https://explorer.celo.org/address/0x9995cc8F20Db5896943Afc8eE0ba463259c931ed/transactions)

**Pull request merged**
